services:
  elasticsearch:
    image: elasticsearch:8.0.1
    container_name: elasticsearch
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xmx500M -Xms500M"
      - bootstrap.memory_local=true
      - cluster.name=adlp-cluster
      - discovery.type=single-node
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: kibana:5.3
    container_name: kibana
    depends_on:
      elasticsearch:
          condition: service_healthy
    ports:
     - "5601:5601"
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
     - XPACK_MONITORING_ENABLED=false
    networks:
      - esnet
networks:
  esnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
volumes:
  esdata:
    driver: local